service:
  port: 9998
  host: localhost

channel_config:
  log_source_consumer_size: 10000
  behavior_source_consumer_size: 10000
  message_size: 10000

endpoint:
  get_job: http://localhost:9090/api/v1/jobs/profiling

kafka:
  group_id: ueba-profiling-test-24
